{% set version = "1.0.4" %}
{% set buildnumber = 0 %}
{% set sha256 = "7e568d7b6c5f0b22eb3acd60a7dfadac37483b58083035b78e9f929083fa5d81" %}

package:
    name: mkl_fft
    version: {{ version }}

source:
    url: https://github.com/IntelPython/mkl_fft/archive/v{{version}}.tar.gz
    sha256: 139e99aaad622f348d37b729bbaa0895c73e344902b38e7e73a3d02528dcdf04

build:
    number: {{buildnumber}}

requirements:
    build:
      - {{ compiler('c') }}
      - {{ compiler('cxx') }}
    host:
      - python
      - setuptools
      - mkl-devel
      - cython
      - numpy-devel 1.11.*
    run:
      - python

test:
    commands:
      - nosetests -v mkl_fft
    requires:
      - nose
    imports:
      - mkl_fft
      - mkl_fft._numpy_fft
      - mkl_fft._scipy_fft

about:
    home: http://github.com/IntelPython/mkl_fft
    license: BSD 3-Clause
    license_file: LICENSE.txt
    description:
        NumPy-based implementation of Fast Fourier Transform using Intel (R) Math Kernel Library.
        Supports in-place and out-of-place, 1D and ND complex FFT on arrays of single and double precision
        with arbitrary memory layout, so long as array strides are multiples of its itemsize. 
    summary: NumPy-based implementation of Fast Fourier Transform using Intel (R) Math Kernel Library.

extra:
  recipe-maintainers:
     - oleksandr-pavlyk
