{% set version = "2.0.0" %}

package:
  name: mkl_fft
  version: {{ version }}

source:
  url: https://github.com/IntelPython/mkl_fft/archive/v{{version}}.tar.gz
  sha256: 539f4a3828e57df2f7b31eb06fddaa64a7d8de469afe10caa14365aeb62f0dad
  patches:
    - patches/0001-enable-python-3.14.patch

build:
  number: 0
  skip: true  # [not x86]
  skip: true  # [py<39 or osx]
  script: {{PYTHON}} -m pip install --no-build-isolation --no-deps .
  script_env:
    - MKLROOT={{PREFIX}}

requirements:
  build:
    - {{ stdlib('c') }}  # [linux]
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - setuptools >=77
    - mkl-devel
    - cython
    - numpy-base {{ numpy }}
  run:
    - python
    - mkl-service
    - numpy >=1.26.4
  run_constrained:
    - scipy >=1.10

test:
  commands:
    - pytest -v --pyargs mkl_fft
    - pip check
  requires:
    - pytest
    - pip
  imports:
    - mkl_fft
    - mkl_fft._numpy_fft
    - mkl_fft._scipy_fft
    - mkl_fft.interfaces
    - mkl_fft.interfaces.numpy_fft
    - mkl_fft.interfaces.scipy_fft

about:
  home: https://github.com/IntelPython/mkl_fft
  license: BSD-3-Clause
  license_file: LICENSE.txt
  license_family: BSD
  description:
    - NumPy-based implementation of Fast Fourier Transform using Intel (R) Math Kernel Library.
    - Supports in-place and out-of-place, 1D and ND complex FFT on arrays of single and double precision
    - with arbitrary memory layout, so long as array strides are multiples of its itemsize.
  summary: NumPy-based implementation of Fast Fourier Transform using Intel (R) Math Kernel Library.
  dev_url: https://github.com/IntelPython/mkl_fft
  doc_url: https://github.com/IntelPython/mkl_fft

extra:
  skip-lints:
    - cbc_dep_in_run_missing_from_host
  recipe-maintainers:
    - oleksandr-pavlyk
